[package]
name = "SpotSign"
version = "0.1.0"
authors = ["jaredkerim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1.0.0-pre.1"
rand = "0.6.0"